user www-data;
worker_processes auto;
pid /run/nginx.pid;
events { worker_connections 2048; }
http {
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;
    sendfile on;
    keepalive_timeout 65;
    server {
        listen 80;
        listen 443 ssl;
        server_name sdwan-lab.local;
        root /srv/www;
        ssl_certificate /etc/nginx/tls/lab.crt;
        ssl_certificate_key /etc/nginx/tls/lab.key;
        location / { try_files $uri =404; }
        location = /healthz { return 200 "ok\n"; }
    }
}


